version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  goapp:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: goapp
    ports:
      - "1323:1323"  # Updated to match the port your Go application listens on
    depends_on:
      - mongodb
    environment:
      - MONGO_URI=mongodb://root:example@mongodb:27017
    volumes:
      - ./config.yml:/root/config.yml  # Mount only the config file

volumes:
  mongo-data:
